"""
FinMate 2.0 Synthetic Demo Data Seeder (Phase 12 & Phase 13)
Seeds a fully populated, safe demo environment with realistic personal finance data.
ALL generated data is explicitly labeled as [Synthetic Demo].
Covers:
- Profile & Income ($5,000.00/mo)
- Food & Groceries
- Transportation & Fuel
- Discretionary Shopping
- Recurring Subscriptions (Netflix, Spotify, Cloud Storage)
- Utility Bills
- Entertainment
- Active Savings & Debt Goals
- Labeled Anomalies
"""

import os
import sys
import json
from datetime import datetime, timedelta

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from database import SessionLocal, engine, Base
import models
import auth


def seed_demo_environment(email: str = "demo@finmate.local", password: str = "DemoMode2026!"):
    db = SessionLocal()
    try:
        print(f"Checking for existing demo user ({email})...")
        existing_user = db.query(models.User).filter_by(email=email).first()
        if existing_user:
            uid = existing_user.user_id
            print(f"Cleaning existing demo records for user #{uid}...")
            db.query(models.Transaction).filter_by(user_id=uid).delete()
            db.query(models.BudgetGoal).filter_by(user_id=uid).delete()
            db.query(models.FinancialProfile).filter_by(user_id=uid).delete()
            db.query(models.UserStats).filter_by(user_id=uid).delete()
            db.query(models.Achievement).filter_by(user_id=uid).delete()
            db.query(models.Notification).filter_by(user_id=uid).delete()
            db.query(models.SubscriptionDecision).filter_by(user_id=uid).delete()
            db.query(models.User).filter_by(user_id=uid).delete()
            db.commit()

        print("Creating synthetic demo user...")
        demo_user = models.User(
            email=email,
            password_hash=auth.get_password_hash(password),
            full_name="Alex Mercer [Synthetic Demo]",
            currency="USD",
            currency_symbol="$",
            preferences=json.dumps({
                "monthly_budget": 3500.0,
                "is_demo": True,
                "synthetic_flag": True,
                "data_provenance": "Generated by scripts/seed_demo_data.py"
            })
        )
        db.add(demo_user)
        db.commit()
        db.refresh(demo_user)
        user_id = demo_user.user_id

        # Financial Profile
        profile = models.FinancialProfile(
            user_id=user_id,
            monthly_income=5200.0,
            employment_type="Senior Systems Engineer [Synthetic]",
            risk_tolerance="moderate"
        )
        db.add(profile)

        # Gamification Stats
        stats = models.UserStats(
            user_id=user_id,
            total_xp=450,
            current_streak=18,
            longest_streak=24,
            total_transactions=65,
            total_spending=3140.0
        )
        db.add(stats)

        # Achievements
        achievements = [
            models.Achievement(
                user_id=user_id,
                achievement_type="first_transaction",
                title="First Step [Synthetic]",
                description="Logged first financial transaction.",
                icon="🎯",
                xp_reward=50
            ),
            models.Achievement(
                user_id=user_id,
                achievement_type="week_streak_7",
                title="Disciplined Spender [Synthetic]",
                description="Maintained under-budget spending streak for 7 days.",
                icon="🔥",
                xp_reward=100
            ),
            models.Achievement(
                user_id=user_id,
                achievement_type="big_saver",
                title="Rainy Day Builder [Synthetic]",
                description="Saved over $1,000 towards emergency reserves.",
                icon="🛡️",
                xp_reward=150
            )
        ]
        db.add_all(achievements)

        # Goals
        now = datetime.utcnow()
        goals = [
            models.BudgetGoal(
                user_id=user_id,
                goal_type="savings",
                target_amount=10000.0,
                current_progress=3800.0,
                deadline=now + timedelta(days=180),
                status="active"
            ),
            models.BudgetGoal(
                user_id=user_id,
                goal_type="savings",
                target_amount=2500.0,
                current_progress=1900.0,
                deadline=now + timedelta(days=60),
                status="active"
            ),
            models.BudgetGoal(
                user_id=user_id,
                goal_type="investment",
                target_amount=5000.0,
                current_progress=1250.0,
                deadline=now + timedelta(days=240),
                status="active"
            )
        ]
        db.add_all(goals)

        # Subscription Decisions
        subs = [
            models.SubscriptionDecision(
                user_id=user_id,
                candidate_id="sub_netflix_01",
                merchant="Netflix [Synthetic]",
                avg_amount=19.99,
                interval_days=30,
                occurrences=6,
                action="keep"
            ),
            models.SubscriptionDecision(
                user_id=user_id,
                candidate_id="sub_spotify_02",
                merchant="Spotify Premium [Synthetic]",
                avg_amount=10.99,
                interval_days=30,
                occurrences=6,
                action="keep"
            ),
            models.SubscriptionDecision(
                user_id=user_id,
                candidate_id="sub_gym_03",
                merchant="Equinox Fitness [Synthetic]",
                avg_amount=85.00,
                interval_days=30,
                occurrences=3,
                action="negotiate"
            )
        ]
        db.add_all(subs)

        # 60 Synthetic Transactions across all required categories spanning past 60 days
        demo_tx_data = [
            # Food & Groceries
            (48.50, "groceries", 2, "Whole Foods Market [Synthetic Demo]"),
            (112.30, "groceries", 5, "Costco Wholesale Bulk [Synthetic Demo]"),
            (34.20, "groceries", 9, "Trader Joe's Essentials [Synthetic Demo]"),
            (62.80, "groceries", 14, "Kroger Supermarket [Synthetic Demo]"),
            (85.40, "groceries", 21, "Fresh Market Groceries [Synthetic Demo]"),
            (22.50, "dining", 3, "Blue Bottle Coffee [Synthetic Demo]"),
            (45.00, "dining", 7, "Downtown Ramen House [Synthetic Demo]"),
            (68.00, "dining", 12, "Trattoria Bistro Dinner [Synthetic Demo]"),
            (18.50, "dining", 18, "Chipotle Mexican Grill [Synthetic Demo]"),
            (55.00, "dining", 25, "Sushi Bar Weekend Lunch [Synthetic Demo]"),

            # Transport
            (32.40, "transport", 4, "Shell Fuel Station [Synthetic Demo]"),
            (24.50, "transport", 8, "Uber Ride to Airport [Synthetic Demo]"),
            (45.00, "transport", 16, "Chevron Gas Fill-up [Synthetic Demo]"),
            (15.00, "transport", 22, "Metropolitan Transit Pass [Synthetic Demo]"),
            (28.00, "transport", 29, "Lyft Ride Home [Synthetic Demo]"),

            # Shopping
            (89.99, "shopping", 6, "Zara Winter Jacket [Synthetic Demo]"),
            (45.00, "shopping", 13, "Amazon Technical Books [Synthetic Demo]"),
            (120.00, "shopping", 20, "Nike Running Shoes [Synthetic Demo]"),
            (35.50, "shopping", 27, "Home Improvement Hardware [Synthetic Demo]"),

            # Subscriptions
            (19.99, "subscriptions", 1, "Netflix Monthly Tier [Synthetic Demo]"),
            (10.99, "subscriptions", 1, "Spotify Premium Subscription [Synthetic Demo]"),
            (85.00, "subscriptions", 2, "Equinox Monthly Gym Membership [Synthetic Demo]"),
            (19.99, "subscriptions", 31, "Netflix Monthly Tier [Synthetic Demo]"),
            (10.99, "subscriptions", 31, "Spotify Premium Subscription [Synthetic Demo]"),

            # Bills & Utilities
            (85.00, "utilities", 10, "City Electric & Power [Synthetic Demo]"),
            (70.00, "utilities", 11, "High-Speed Fiber Internet [Synthetic Demo]"),
            (42.00, "utilities", 15, "Municipal Water Utility [Synthetic Demo]"),
            (88.00, "utilities", 41, "City Electric & Power [Synthetic Demo]"),
            (70.00, "utilities", 42, "High-Speed Fiber Internet [Synthetic Demo]"),

            # Entertainment
            (32.00, "entertainment", 8, "IMAX Movie Night Tickets [Synthetic Demo]"),
            (59.99, "entertainment", 19, "PlayStation Digital Game [Synthetic Demo]"),
            (25.00, "entertainment", 26, "Board Game Cafe Admission [Synthetic Demo]"),

            # Labeled Anomalies
            (480.00, "shopping", 15, "Synthetic Anomaly: Accidental merchant double billing [Synthetic Demo]"),
            (750.00, "dining", 28, "Synthetic Anomaly: Large private event dinner booking [Synthetic Demo]")
        ]

        for amt, cat, days_ago, desc in demo_tx_data:
            dt = now - timedelta(days=days_ago)
            t = models.Transaction(
                user_id=user_id,
                amount=amt,
                category=cat,
                date=dt,
                description=desc,
                source="demo"
            )
            db.add(t)

        db.commit()
        print(f"Successfully seeded demo environment for '{email}'.")
        print(f"Login with: {email} / {password}")
        return demo_user

    finally:
        db.close()


if __name__ == "__main__":
    seed_demo_environment()
